version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  labels:
  - Help Wanted
  - dependencies
  - php
  - À relire
  - À tester
  ignore:
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.58
    - 0.12.70
    - 0.12.80
  - dependency-name: atoum/atoum
    versions:
    - 3.4.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  labels:
  - Help Wanted
  - dependencies
  - javascript
  - À relire
  - À tester
